In [23]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [24]:
df = pd.read_csv ('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/refs/heads/master/mtcars.csv')

In [25]:
df.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [26]:
df.tail()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

In [28]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [29]:
df.shape

(32, 12)

In [31]:
df.columns

Index(['Unnamed: 0', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  32 non-null     object
 1   mpg         32 non-null     float64
 2   cyl         32 non-null     int64
 3   disp        32 non-null     float64
 4   hp          32 non-null     int64
 5   drat        32 non-null     float64
 6   wt          32 non-null     float64
 7   qsec        32 non-null     float64
 8   vs          32 non-null     int64
 9   am          32 non-null     int64
 10  gear        32 non-null     int64
 11  carb        32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

In [34]:
df.dtypes

Unnamed: 0     object
mpg           float64
cyl             int64
disp          float64
hp              int64
drat          float64
wt            float64
qsec          float64
vs              int64
am              int64
gear            int64
carb            int64
dtype: object

In [35]:
type(df)

pandas.core.frame.DataFrame

In [36]:
df.rename(columns={'Unnamed: 0':'car_names'}, inplace=True)

In [37]:
df.columns

Index(['car_names', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [38]:
df2 = df[['mpg', 'hp', 'wt', 'cyl']]

In [39]:
df2.head()

    mpg   hp     wt  cyl
0  21.0  110  2.620    6
1  21.0  110  2.875    6
2  22.8   93  2.320    4
3  21.4  110  3.215    6
4  18.7  175  3.440    8

In [43]:
df2.rename(columns={'cyl':'cylinders', 'wt':'weight', 'hp':'horsepower', 'mpg':'miles_per_gallon'}, inplace=True)

/tmp/ipykernel_1963/1781155013.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.rename(columns={'cyl':'cylinders', 'wt':'weight', 'hp':'horsepower', 'mpg':'miles_per_gallon'}, inplace=True)

In [44]:
df2.head()

   miles_per_gallon  horsepower  weight  cylinders
0              21.0         110   2.620          6
1              21.0         110   2.875          6
2              22.8          93   2.320          4
3              21.4         110   3.215          6
4              18.7         175   3.440          8

In [45]:
#summary statistics
df2.describe()

       miles_per_gallon  horsepower     weight  cylinders
count         32.000000   32.000000  32.000000  32.000000
mean          20.090625  146.687500   3.217250   6.187500
std            6.026948   68.562868   0.978457   1.785922
min           10.400000   52.000000   1.513000   4.000000
25%           15.425000   96.500000   2.581250   4.000000
50%           19.200000  123.000000   3.325000   6.000000
75%           22.800000  180.000000   3.610000   8.000000
max           33.900000  335.000000   5.424000   8.000000

In [46]:
df2['miles_per_gallon'].mean()

np.float64(20.090625000000003)

In [47]:
#filter data and find summary statistics
df_8cyl = df2[df2['cylinders'] == 8]

In [48]:
df_8cyl

    miles_per_gallon  horsepower  weight  cylinders
4               18.7         175   3.440          8
6               14.3         245   3.570          8
11              16.4         180   4.070          8
12              17.3         180   3.730          8
13              15.2         180   3.780          8
14              10.4         205   5.250          8
15              10.4         215   5.424          8
16              14.7         230   5.345          8
21              15.5         150   3.520          8
22              15.2         150   3.435          8
23              13.3         245   3.840          8
24              19.2         175   3.845          8
28              15.8         264   3.170          8
30              15.0         335   3.570          8

In [51]:
df_8cyl.describe()

       miles_per_gallon  horsepower     weight  cylinders
count         14.000000   14.000000  14.000000       14.0
mean          15.100000  209.214286   3.999214        8.0
std            2.560048   50.976886   0.759405        0.0
min           10.400000  150.000000   3.170000        8.0
25%           14.400000  176.250000   3.532500        8.0
50%           15.200000  192.500000   3.755000        8.0
75%           16.250000  241.250000   4.013750        8.0
max           19.200000  335.000000   5.424000        8.0